#kubectl create secret generic backend-user --from-literal=backend-username='backend-admin'
---
apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretFrom:
            name: backend-user
            key: backend-username
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
