apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  labels:
    name: secret-test-pod
spec:
  containers:
  - name: secret-test-pod
    image: nginx
    volumeMounts:
      - mountPath: /etc/secret-volume
        name: secret-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
   # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
