apiVersion: v1
kind: Service
metadata:
  name: summer-grpc-provider
spec:
  selector:
    app: summer-grpc-provider
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summer-grpc-provider
spec:
  selector:
    matchLabels:
      app: summer-grpc-provider
  template:
    metadata:
      labels:
        app: summer-grpc-provider
    spec:
      containers:
      - name: summer-grpc-provider
        image: https://hub.docker.com/r/liuweizhenhaoa/summer-grpc-provider:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
