apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: k8s.gcr.io/busybox
    command: ["/bin/sh","-c","cat /etc/config/keys"]
    volumeMounts:
    - name: config-volume
      mountPath:  /etc/config
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: config-name
      configMap:
        name: special-config
        items:
          - key: SPECIAL_LEVEL
            path: keys
