apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-resourcefieldref
  labels:
    name: dapi-envars-resourcefieldref
spec:
  restartPolicy: Never
  containers:
  - name: dapi-envars-resourcefieldref
    image: k8s.gcr.io/busybox:1.24
    command: [ "sh", "-c"]
    args:
    - while true; do
        echo -en '\n';
        printenv MY_CPU_REQUEST MY_CPU_LIMIT;
        printenv MY_MEM_REQUEST MY_MEM_LIMIT;
        sleep 10;
      done;
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: MY_CPU_REQUEST
        valueFrom:
          resourceFieldRef:
            containerName: test-container
            resource: requests.cpu
      - name: MY_CPU_LIMIT
        valueFrom:
          resourceFieldRef:
            containerName: test-container
            resource: limits.cpu
      - name: MY_MEM_REQUEST
        valueFrom:
          resourceFieldRef:
            containerName: test-container
            resource: requests.memory
      - name: MY_MEM_LIMIT
        valueFrom:
          resourceFieldRef:
            containerName: test-container
            resource: limits.memory
    ports:
      - containerPort: 80
