apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    name: envar-demo
spec:
  restartPolicy: Never
  containers:
  - name: envar-demo
    image: gcr.io/google-samples/node-hello:1.0
    env:
      - name: DEMO_GREETING
        value: "Hello from the environment"
      - name: DEMO_FAREWELL
        value: "Such a sweet sorrow"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80