apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  restartPolicy: OnFailure
  containers:
  - name: command-demo-container
    image: debian
    env:
      - name: MESSAGE
        value: "hello world"
    command: ["printenv"]
    args:
      - "HOSTNAME"
      - "KUBERNETES_PORT"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

