apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    name: liveness-http
    test: liveness
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
      - "/server"
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3 
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 30
      periodSeconds: 10
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
