apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
        cpu: "1"
      defaultRequest:
        memory: 256Mi
        cpu: "0.5"
