apiVersion: v1
kind: Pod
metadata:
  name: constraints-mem-demo
  labels:
    name: constraints-mem-demo
spec:
  containers:
  - name: constraints-mem-demo
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "500m"
      requests:
        memory: "500Mi"
    ports:
      - containerPort: 80
