apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
spec:
  limits:
    - type: Container
      max:
        memory: 1Gi
        cpu: "1"
      min:
        memory: 500Mi
        cpu: "0.5"
