apiVersion: networking.k8s.io/v1
kind: NetworkPlicy
metadata:
  name: access-nginx
spec:
  podSelector:
    matchLabels:
      app: niginx
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"
