apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  - name: shell
    image: k8s.gcr.io/busybox
    securityContext:
      capabilities:
        add:
          - "SYS_PTRACE"
    stdin: true
    tty: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 81
